baseURL = 'https://sjsanc.com'
languageCode = 'en-us'
title = 'sjsanc'

[outputs]
    home = ["html"]

[[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[markup]
    [markup.highlight]
        style = 'github'